<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>cushy</string>
	<key>scopeName</key>
	<string>source.cushy</string>
	<key>foldingStartMarker</key>
	<string>(@begin|@&lt;|@if)</string>
	<key>foldingStopMarker</key>
	<string>(@end|@&gt;|@endif)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#root</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>root</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#makaron</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyValueList</string>
				</dict>
			</array>
		</dict>
		<key>keyValueList</key>
		<dict>
			<key>name</key>
			<string>meta.key.value.list.cushy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>key</key>
		<dict>
			<key>name</key>
			<string>meta.key.value.cushy</string>
			<key>begin</key>
			<string>[a-zA-Z$_][a-zA-Z0-9$_]*(?=\s*:)</string>
			<key>end</key>
			<string>(?=[}\n])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.label.cushy</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>name</key>
			<string>meta.value.cushy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#makaron</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<key>block</key>
		<dict>
			<key>name</key>
			<string>meta.block.cushy</string>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keyValueList</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.cushy</string>
					<key>begin</key>
					<string>/\*\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.cushy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.cushy</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.cushy</string>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.cushy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.cushy</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*(?=[\n])</string>
					<key>name</key>
					<string>comment.line.double-slash.cushy</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>name</key>
			<string>meta.structure.string.cushy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringEscape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringEscape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>stringEscape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#makaron</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\l[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.bigint</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.unicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\x[0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.hex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[0-9]+</string>
					<key>name</key>
					<string>constant.character.escape.decimal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.template</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\[var\]</string>
							<key>end</key>
							<string>\[/var\]</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.begin</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.end</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>variable.other.cushy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#makaron</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[mac\]</string>
							<key>end</key>
							<string>\[/mac\]</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.begin</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.end</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>string.other.cushy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#stringEscape</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[windows\]</string>
							<key>end</key>
							<string>\[/windows\]</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.begin</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.end</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>string.other.cushy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#stringEscape</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[xlate\]</string>
							<key>end</key>
							<string>\[/xlate\]</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.begin</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.end</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>string.other.cushy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#stringEscape</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[uppercase\]</string>
							<key>end</key>
							<string>\[/uppercase\]</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.begin</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.end</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>string.other.cushy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#stringEscape</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[lowercase\]</string>
							<key>end</key>
							<string>\[/lowercase\]</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.begin</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.end</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>string.other.cushy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#stringEscape</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[trim\]</string>
							<key>end</key>
							<string>\[/trim\]</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.begin</string>
								</dict>
							</dict>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.template-expression.end</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>string.other.cushy</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#stringEscape</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex</string>
					<key>match</key>
					<string>[-+]?0x[0-9A-Fa-f]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
					<key>match</key>
					<string>[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?(\s*%)?</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language</string>
					<key>match</key>
					<string>\b(w|h|true|false)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language</string>
					<key>match</key>
					<string>\$</string>
				</dict>
			</array>
		</dict>
		<key>makaron</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literalAt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macroDefinition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#valueDefinition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ifStatement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#includeFile</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invokeMacro</string>
				</dict>
			</array>			
		</dict>
		<key>literalAt</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.makaron</string>
					<key>match</key>
					<string>@@</string>
				</dict>
			</array>
		</dict>
		<key>macroDefinition</key>
		<dict>
			<key>name</key>
			<string>meta.function.makaron</string>
			<key>begin</key>
			<string>(@begin)\b\s+([a-zA-Z$_][a-zA-Z0-9$_]*)</string>
			<key>end</key>
			<string>(@end)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.makaron</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.makaron</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.makaron</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macroName</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#root</string>
				</dict>
			</array>
		</dict>
		<key>macroName</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=[a-zA-Z0-9$_])\(</string>
			<key>end</key>
			<string>\)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.makaron</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#paramsList</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#root</string>
				</dict>
			</array>
		</dict>
		<key>paramsList</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.makaron</string>
					<key>match</key>
					<string>[a-zA-Z$_][a-zA-Z0-9$_]*</string>
				</dict>
			</array>
		</dict>
		<key>raw</key>
		<dict>
			<key>begin</key>
			<string>@&lt;</string>
			<key>end</key>
			<string>@&gt;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.makaron</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.raw.cushy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literalAt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#root</string>
				</dict>
			</array>
		</dict>
		<key>balanced</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.structure.balanced.paranthesis.makaron</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#root</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.structure.balanced.braces.makaron</string>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#root</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.structure.balanced.brackets.makaron</string>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#root</string>
						</dict>
					</array>
				</dict>

				<dict>
					<key>name</key>
					<string>string.quoted.double.makaron</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringEscape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.makaron</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringEscape</string>
						</dict>
					</array>
				</dict>

			</array>
		</dict>
		<key>valueDefinition</key>
		<dict>
			<key>name</key>
			<string>meta.define.makaron</string>
			<key>begin</key>
			<string>(@(?:re)?define)\b\s+([a-zA-Z$_][a-zA-Z0-9$_]*)(\s*\=)</string>
			<key>end</key>
			<string>(?=[\n])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.macro.makaron</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.macro.makaron</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.makaron</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.terminator.statement.makaron</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#root</string>
				</dict>
			</array>
		</dict>
		<key>ifStatement</key>
		<dict>
			<key>name</key>
			<string>meta.block.conditional.makaron</string>
			<key>begin</key>
			<string>@if</string>
			<key>end</key>
			<string>@endif</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.makaron</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#condition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ifStatement</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.makaron</string>
					<key>match</key>
					<string>(@elif|@else)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#root</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>name</key>
			<string>meta.expression.makaron</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literalAt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#balanced</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invokeMacro</string>
				</dict>
			</array>
		</dict>
		<key>condition</key>
		<dict>
			<key>name</key>
			<string>meta.block.condition.makaron</string>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.makaron</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.compare.makaron</string>
					<key>match</key>
					<string>(==|!=)</string>
				</dict>
			</array>
		</dict>
		<key>invokeMacro</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.macro.invoke.makaron</string>
					<key>begin</key>
					<string>@[a-zA-Z$_][a-zA-Z0-9$_]*\(</string>
					<key>end</key>
					<string>\)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.makaron</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.macro.makaron</string>
					<key>match</key>
					<string>@[a-zA-Z$_][a-zA-Z0-9$_]*\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.macro.indirect.makaron</string>
					<key>begin</key>
					<string>@\(</string>
					<key>end</key>
					<string>\)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.other.makaron</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.other.makaron</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>includeFile</key>
		<dict>
			<key>name</key>
			<string>meta.include.makaron</string>
			<key>begin</key>
			<string>(@include\b)\s+</string>
			<key>end</key>
			<string>(?=[\n])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.include.makaron</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.terminator.statement.makaron</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
