<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>cushyschema</string>
    <key>scopeName</key>
    <string>source.schema</string>
    <key>fileTypes</key>
    <array>
        <string>schema</string>
    </array>
    <key>patterns</key>
    <array>
        <dict>
            <key>name</key>
            <string>keyword.control.schema</string>
            <key>match</key>
            <string>(\(|\)|\[|\]|\||&lt;-|\.\.\.|=|\?(file:)?|{|}|\\|include:|resources:)</string>
        </dict>
        <dict>
            <key>name</key>
            <string>string.quoted.schema</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
        </dict>
        <dict>
            <key>name</key>
            <string>string.quoted.schema</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
        </dict>
        <dict>
            <key>name</key>
            <string>entity.name.schema</string>
            <key>begin</key>
            <string>&lt;</string>
            <key>end</key>
            <string>&gt;</string>
        </dict>
        <dict>
            <key>name</key>
            <string>entity.name.schema</string>
            <key>match</key>
            <string>(\*|%)([_a-zA-Z$_][a-zA-Z$_0-9]*)?</string>
        </dict>
        <dict>
            <key>name</key>
            <string>entity.name.schema</string>
            <key>match</key>
            <string>[_a-zA-Z$_][a-zA-Z$_0-9]*\s+&lt;-</string>
        </dict>
        <dict>
            <key>name</key>
            <string>comment.block.schema</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
        </dict>
        <dict>
            <key>name</key>
            <string>comment.line.schema</string>
            <key>match</key>
            <string>//.*$</string>
        </dict>
        <dict>
            <key>name</key>
            <string>variable.name.schema</string>
            <key>match</key>
            <string>[_a-zA-Z_][a-zA-Z_0-9]*:</string>
        </dict>
    </array>
</dict>
</plist>
           