<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>impd</string>
	<key>scopeName</key>
	<string>source.impd</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#impd</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>impd</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#stringEscape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
			</array>
		</dict>
		<key>group</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.group.impd</string>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#impd</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.expression.impd</string>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#impd</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.impd</string>
					<key>begin</key>
					<string>/\*\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.impd</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.impd</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.impd</string>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.impd</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.impd</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*(?=[
])</string>
					<key>name</key>
					<string>comment.line.double-slash.impd</string>
				</dict>
			</array>
		</dict>
		<key>assignment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.impd</string>
					<key>match</key>
					<string>\b[a-zA-Z$_][a-zA-Z0-9$_]*(?=\s*=\s*)</string>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>entity.name.label.impd</string>
					<key>match</key>
					<string>\b[a-zA-Z$_][a-zA-Z0-9$_]*(?=\s*:)</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.other.impd</string>
					<key>match</key>
					<string>[$][a-zA-Z0-9$_.]+</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.impd</string>
					<key>match</key>
					<string>(?i)\b(yes|no)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.impd</string>
					<key>match</key>
					<string>(?i)\b(pi)\b</string>
				</dict>
			</array>
		</dict>
		<key>instruction</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\bformat\s*(\S*)\s*requires\s*:\s*(\S*)</string>
					<key>end</key>
					<string>(?=.)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.impd</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.impd</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.impd</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.function.impd</string>
					<key>match</key>
					<string>(?i)\b(format|meta|debug|trace|stop|call|include|local|return|if|repeat|for)\b</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex.impd</string>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9])0x[0-9A-Fa-f]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.impd</string>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9])[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?(\s*%)?</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.math.impd</string>
					<key>match</key>
					<string>(?i)\b(abs|acos|asin|atan|ceil|cos|cosh|exp|floor|log|log10|sin|sinh|sqrt|tan|tanh)(?=\()</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.other.impd</string>
					<key>match</key>
					<string>(?i)\b(len)(?=\()</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.impd</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringEscape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>stringEscape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\U[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.bigint.impd</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.unicode.impd</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\x[0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.hex.impd</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[0-9]+</string>
					<key>name</key>
					<string>constant.character.escape.decimal.impd</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.impd</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
