<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>name</key>
	<string>ivg</string>
	<key>scopeName</key>
	<string>source.ivg</string>
    <key>fileTypes</key>
    <array>
        <string>ivg</string>
    </array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.impd#stringEscape</string>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.group.ivg</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ivg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.impd</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.color.ivg</string>
			<key>match</key>
			<string>(?&lt;![a-zA-Z0-9])#[0-9A-Fa-f]{6,8}</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.hex.ivg</string>
			<key>match</key>
			<string>(?&lt;![a-zA-Z0-9])#[0-9A-Fa-f]{2}</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.colors.ivg</string>
			<key>match</key>
			<string>(?i)\b(none|aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.other.ivg</string>
			<key>match</key>
			<string>(?i)\b(linear|radial|butt|round|square|bevel|curve|miter|non-zero|even-odd|left|center|right|top|middle|bottom left|center|right)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.color.ivg</string>
			<key>match</key>
			<string>(?i)\b(rgb|hsv)(?=\()</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.instruction.ivg</string>
			<key>match</key>
			<string>(?i)\b(rect|line|ellipse)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.instruction.ivg</string>
			<key>match</key>
			<string>(?i)\b(bounds|context|options|pen|fill|mask|reset|RECT|ELLIPSE|STAR|PATH|WIPE)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.transformation.ivg</string>
			<key>match</key>
			<string>(?i)\b(offset|scale|rotate|shear|matrix)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.instruction.ivg</string>
			<key>match</key>
			<string>(?i)\b(define\s+font|define\s+image|font|TEXT|IMAGE)\b</string>
		</dict>
	</array>
	<key>repository</key>
	<dict/>
</dict>
</plist>
